address review feedback

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,7 +60,12 @@ jobs:
       - run:
           name: Build
           command: |
-            ./ci-build.sh
+            if [[ -z "$ALGOLIA_API_KEY" || -z "$ALGOLIA_INDEX_NAME" ]]
+            then
+              printf 'ERROR: %s\n' 'Algolia API key or index name not set.' >&2
+              exit 1
+            fi
+            yarn build
       - persist_to_workspace:
           root: .
           paths:
